// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package rest

import (
	"wantum/pkg/api/handler/rest/user"
	user4 "wantum/pkg/api/usecase/user"
	"wantum/pkg/domain/repository"
	"wantum/pkg/domain/service/file"
	profile2 "wantum/pkg/domain/service/profile"
	user3 "wantum/pkg/domain/service/user"
	user2 "wantum/pkg/infrastructure/mysql/user"
	"wantum/pkg/infrastructure/mysql/userprofile"
)

// Injectors from wire.go:

func InitUserAPI(masterTxManager repository.MasterTxManager) user.Server {
	userRepository := user2.New(masterTxManager)
	service := user3.New(userRepository)
	profileRepository := userprofile.New(masterTxManager)
	profileService := profile2.New(profileRepository)
	fileService := file.New()
	interactor := user4.New(masterTxManager, service, profileService, fileService)
	server := user.New(interactor)
	return server
}
