version: '3.5'
services:
  db:
    image: mysql:5.7
    container_name: wantum_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wantum
      MYSQL_USER: worker
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always