version: '3.5'
services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      target: build
    container_name: wantum_api
    environment:
      MYSQL_USER: worker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wantum
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - .:/go/src/wantum
    ports:
      - 8080:8080
    restart: always
    command: realize start

  db:
    image: mysql:5.7
    container_name: wantum_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wantum
      MYSQL_USER: worker
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always