const UserResourceBuilder = require("./user");
const PhotoResourceBuilder = require("./photo");
const TagResourceBuilder = require("./tag");

module.exports = class MemoryResourceBuilder {
  constructor() {
    this.memoryId = 1;
    this.activity = "hogehoge";
    this.date = 1600513200;
    this.description = "fugafuga";
    this.place = "hogefuga";
    this.albumId = 1;
    this.author = new UserResourceBuilder().build();
    this.photos = [];
    this.tags = [];
  }

  build() {
    return {
      memory_id: this.memoryId,
      activity: this.activity,
      date: this.date,
      description: this.description,
      place: this.place,
      author: this.author,
      photos: this.photos,
      tags: this.tags
    };
  }

  /**
   * 
   * @param {Number} memoryId 
   */
  withMemoryId(memoryId) {
    this.memoryId = memoryId;
    return this;
  }
  
  withActivity(activity) {
    this.activity = activity;
    return this;
  }

  withDate(date) {
    this.date = date;
    return this;
  }
  
  withDescription(description) {
    this.description = description;
    return this;
  }
  
  withPlace(place) {
    this.place = place;
    return this;
  }

  withAlbumId(albumId) {
    this.albumId = albumId;
    return this;
  }
  
  /**
   * buildした後のuserを引数に取ります
   * 
   * @param {*} user
   */
  withAuthor(user) {
    this.author = user;
    return this;
  }
  
  /**
   * 全ての要素をbuildした状態にして下さい
   * 
   * @param {*} photos 
   */
  withPhotos(photos) {
    this.photos = photos;
    return this;
  }

  /**
   * 指定された数だけphotoを生成
   * 
   * @param {Number} count 
   */
  withAutoGeneratedPhotos(count) {
    for (var i = 0; i < count; i++) {
      this.photos.push(new PhotoResourceBuilder()
        .withPhotoId(i + 1)
        .withPhotoUrl(`http://example.com/hogehoge${i + 1}.png`)
        .build());
    }
    return this;
  }
  
  /**
   * 全ての要素をbuildした状態にしてください
   * 
   * @param {*} tags 
   */
  withTags(tags) {
    this.tags = tags;
    return this;
  }

  /**
   * 指定された数だけtagを生成
   * 
   * @param {Number} count 
   */
  withAutoGeneratedTags(count) {
    for (var i = 0; i < count; i++) {
      this.tags.push(new TagResourceBuilder()
        .withTagId(i + 1)
        .withTagName(`tag${i + 1}`)
        .build());
    }
    return this;
  }

  /**
   * buildした後のtagを引数に取ります
   * @param {*} tag 
   */
  appendTag(tag) {
    this.tags.push(tag);
    return this;
  }

  /**
   * buildした後のphotoを引数に取ります
   * @param {*} photo 
   */
  appendPhoto(photo) {
    this.photos.push(photo);
    return this;
  }
};