const UserResourceBuilder = require("./user");
const WishCategoryResourceBuilder = require("./wishCategory");

module.exports = class WishBoardResourceBuilder {
  constructor() {
    this.wishBoardId = 1;
    this.title = "hogehoge";
    this.wishCategories = [];
    this.authors = [];
    this.inviteUrl = "http://example.com/invite";
    this.backgroundImageUrl = "http://examaple.com/backgroundimage";
  }

  build() {
    return {
      wish_board_id: this.wishBoardId,
      title: this.title,
      wish_categories: this.wishCategories,
      authors: this.authors,
      invite_url: this.inviteUrl,
      background_image_url: this.backgroundImageUrl
    };
  }

  withWishBoardId(id) {
    this.wishBoardId = id;
    return this;
  }

  withTitle(title) {
    this.title = title;
    return this;
  }
  
  withWishCategories(wishCategories) {
    this.wishCategories = wishCategories;
    return this;
  }
  
  /**
   * 指定された数のwish categoryを生成する
   * 
   * @param {Number} count 
   */
  withAutoGeneratedWishCategories(count) {
    for (var i = 0; i < count; i++) {
      this.wishCategories.push(new WishCategoryResourceBuilder()
        .withWishCategoryId(i + 1)
        .withAutoGeneratedWishCards(i)
        .build());
    }
    return this;
  }
  
  withAuthors(authors) {
    this.authors = authors;
    return this;
  }
  
  /**
   * 指定された数のuserを生成します
   * 
   * @param {Number} count 
   */
  withAutoGeneratedAuthors(count) {
    for (var i = 0; i < count; i++) {
      this.authors.push(new UserResourceBuilder()
        .withUserId(i + 1)
        .withUserName(`hogehoge${i + 1}`)
        .build());
    }
    return this;
  }
  
  withInviteUrl(url) {
    this.inviteUrl = url;
    return this;
  }
  
  withBackgroundImageUrl(url) {
    this.backgroundImageUrl = url;
    return this;
  }
};