const resourceUtil = require("./resourceUtil");

module.exports = class WishCategoryResourceBuilder {
  constructor() {
    this.wishCategoryId = 1;
    this.title = "hogehoge";
    this.wishCards = [];
  }

  build() {
    return {
      wish_category_id: this.wishCategoryId,
      title: this.title,
      wish_cards: this.wishCards
    };
  }

  withWishCategoryId(id) {
    this.wishCategoryId = id;
    return this;
  }

  withTitle(title) {
    this.title = title;
    return this;
  }
  
  withWishCards(wishCards) {
    this.wishCards = wishCards;
    return this;
  }
  
  /**
   * 指定された数のwish cardを生成します
   * 
   * @param {Number} count 
   */
  withAutoGeneratedWishCards(count) {
    this.wishCards = resourceUtil.autoGenerateWishCards(count);
    return this;
  }
};