const protoUtil = require("../utility/protoUtil");
const AlbumResourceBuilder = require("../resource/album");

module.exports = class AlbumService {
  constructor() {
    const protoDescriptor = protoUtil.getProtoDescriptor("album.proto");
    this.albumProto = protoDescriptor.proto_album;
  }

  createAlbum(call, callback) {
    callback(
      null,
      new AlbumResourceBuilder()
        .wishTitle(call.request.title)
        .build()
    );
  }

  getAlbum(call, callback) {
    callback(
      null,
      new AlbumResourceBuilder()
        .withAlbumId(call.request.album_id)
        .withAutoGeneratedMemories(10)
        .build()
    );
  }

  getMyAlbums(call, callback) {
    // TODO: 固定値きっしょ
    var albums = [];
    const limit = call.request.limit ? call.request.limit : 5;
    for (var i = 0; i < limit; i++) {
      albums.push(new AlbumResourceBuilder()
        .withAlbumId(i + 1)
        .withAutoGeneratedMemories(5)
        .build());
    }
    callback(
      null,
      { albums: albums }
    );
  }

  changeAlbumTitle(call, callback) {
    // TODO: memoryが固定数だよ〜〜〜
    callback(
      null,
      new AlbumResourceBuilder()
        .withAlbumId(call.request.album_id)
        .wishTitle(call.request.title)
        .withAutoGeneratedMemories(5)
        .build()
    );
  }

  deleteAlbum(call, callback) {
    callback(null, {});
  }
};