const protoUtil = require("../utility/protoUtil");
const MemoryResourceBuilder = require("../resource/memory");

module.exports = class TimelineService {
  constructor() {
    const protoDescriptor = protoUtil.getProtoDescriptor("time_line.proto");
    this.timelineProto = protoDescriptor.proto_timeline;
  }

  getTimeLine(call, callback) {
    var memories = [];
    // TODO: 固定値...
    for (var i = 0; i < 10; i++) {
      memories.push(new MemoryResourceBuilder()
        .withMemoryId(i + 1)
        .withAutoGeneratedTags(2)
        .withAutoGeneratedPhotos(2)
        .build());
    }
    callback(
      null,
      { memories: memories }
    );
  }
};