const protoUtil = require("../utility/protoUtil");
const WishBoardResourceBuilder = require("../resource/wishBoard");

module.exports = class WishBoardService {
  constructor() {
    const protoDescriptor = protoUtil.getProtoDescriptor("wish_board.proto");
    this.wishBoardProto = protoDescriptor.proto_wishboard;
  }

  createWishBoard(call, callback) {
    callback(
      null,
      new WishBoardResourceBuilder()
        .withTitle(call.request.title)
        .build()
    );
  }
  
  getWishBoardList(call, callback) {
    // TODO: implement
    callback(null, {});
  }
  
  getWishBoard(call) {
    // NOTE: 取り合えず単発
    call.write(new WishBoardResourceBuilder()
      .withWishBoardId(call.request.wish_board_id)
      .withAutoGeneratedAuthors(2)
      .withAutoGeneratedWishCategories(2)
      .build());
    call.end();
  }
  
  updateWishBoardName(call, callback) {
    callback(
      null,
      new WishBoardResourceBuilder()
        .withWishBoardId(call.request.wish_board_id)
        .withAutoGeneratedAuthors(2)
        .withAutoGeneratedWishCategories(2)
        .withTitle(call.request.title)
        .build()
    );
  }
  
  updateWishBoardBackgroundImage(call, callback) {
    callback(
      null,
      new WishBoardResourceBuilder()
        .withWishBoardId(call.request.wish_board_id)
        .withAutoGeneratedAuthors(2)
        .withAutoGeneratedWishCategories(2)
        .build()
    );
  }
  
  updateWishCategoryPriority(call, callback) {
    callback(
      null,
      new WishBoardResourceBuilder()
        .withWishBoardId(call.request.wish_board_id)
        .withAutoGeneratedAuthors(2)
        .withAutoGeneratedWishCategories(call.request.position.length)
        .build()
    );
  }
  
  deleteWishBoard(call, callback) {
    callback(null, {});
  }
};