// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/domain/repository/user/repository.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"
	user "wantum/pkg/domain/entity/user"
	repository "wantum/pkg/domain/repository"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// InsertUser mocks base method
func (m *MockRepository) InsertUser(masterTx repository.MasterTx, userEntity *user.Entity) (*user.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", masterTx, userEntity)
	ret0, _ := ret[0].(*user.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUser indicates an expected call of InsertUser
func (mr *MockRepositoryMockRecorder) InsertUser(masterTx, userEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockRepository)(nil).InsertUser), masterTx, userEntity)
}

// SelectByPK mocks base method
func (m *MockRepository) SelectByPK(ctx context.Context, masterTx repository.MasterTx, userID int) (*user.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByPK", ctx, masterTx, userID)
	ret0, _ := ret[0].(*user.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByPK indicates an expected call of SelectByPK
func (mr *MockRepositoryMockRecorder) SelectByPK(ctx, masterTx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByPK", reflect.TypeOf((*MockRepository)(nil).SelectByPK), ctx, masterTx, userID)
}

// SelectByAuthID mocks base method
func (m *MockRepository) SelectByAuthID(ctx context.Context, masterTx repository.MasterTx, authID string) (*user.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByAuthID", ctx, masterTx, authID)
	ret0, _ := ret[0].(*user.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByAuthID indicates an expected call of SelectByAuthID
func (mr *MockRepositoryMockRecorder) SelectByAuthID(ctx, masterTx, authID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByAuthID", reflect.TypeOf((*MockRepository)(nil).SelectByAuthID), ctx, masterTx, authID)
}

// SelectAll mocks base method
func (m *MockRepository) SelectAll(ctx context.Context, masterTx repository.MasterTx) (user.EntitySlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll", ctx, masterTx)
	ret0, _ := ret[0].(user.EntitySlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAll indicates an expected call of SelectAll
func (mr *MockRepositoryMockRecorder) SelectAll(ctx, masterTx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockRepository)(nil).SelectAll), ctx, masterTx)
}
