openapi: 3.0.0
info:
  title: wantum
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{user_id}':
    parameters:
      - schema:
          type: integer
        name: user_id
        in: path
        required: true
    get:
      summary: user get
      tags:
        - users
      responses: {}
      operationId: get-users-user_id
    put:
      summary: user update
      tags:
        - users
      responses: {}
      operationId: put-users-user_id
    delete:
      summary: user delete
      tags:
        - users
      responses: {}
      operationId: delete-users-user_id
  '/wishlists/{wish_list_id}':
    parameters:
      - schema:
          type: integer
        name: wish_list_id
        in: path
        required: true
    get:
      summary: wish_list get
      tags:
        - wish_lists
      responses: {}
      operationId: get-wishlists-wish_list_id
      description: |-
        wish_list詳細情報を取得する。

        そのwish_listに招待されている人だけが見られる。

        category, wish_card をネストしたjsonを返す。
    put:
      summary: wish_list update
      tags:
        - wish_lists
      responses: {}
      operationId: put-wishlists-wish_list_id
      description: |-
        wish_listの更新。

        そのwish_listに招待されている人のみ可能（もしくはホストのみ？）。
    delete:
      summary: wish_list delete
      tags:
        - wish_lists
      responses: {}
      operationId: delete-wishlists-wish_list_id
      description: |-
        wish_listの削除。

        そのwish_listに招待されている人のみ可能（もしくはホストのみ？）。
  /wishlists:
    post:
      summary: wish_list create
      tags:
        - wish_lists
      responses: {}
      operationId: post-wishlists
      description: wish_listの新規作成。
    parameters: []
    get:
      summary: wish_list list get
      operationId: get-wishlists
      responses:
        '200':
          description: OK
      tags:
        - wish_lists
      description: |-
        wish_list一覧。

        自分の所持している全wish_listを返す。

        レスポンスjsonは、category, wish_card をネストしない。
  '/categories/{category_id}':
    parameters:
      - schema:
          type: integer
        name: category_id
        in: path
        required: true
    put:
      summary: category update
      tags:
        - categories
      responses: {}
      operationId: put-categories-category_id
      description: |-
        カテゴリーの更新。

        親のwish_listに招待されている人のみ可能。
    delete:
      summary: category delete
      tags:
        - categories
      responses: {}
      operationId: delete-categories-category_id
      description: |-
        カテゴリーの削除。

        親のwish_listに招待されている人のみ可能。
  /categories:
    parameters: []
    post:
      summary: category create
      tags:
        - categories
      responses: {}
      operationId: post-categories
      description: |-
        カテゴリーの新規作成。

        指定したwish_listに招待されている人のみ可能。
  '/wishcards/{wish_card_id}':
    parameters:
      - schema:
          type: integer
        name: wish_card_id
        in: path
        required: true
    put:
      summary: wish_card update
      tags:
        - wish_cards
      responses: {}
      operationId: put-wishcards-wish_card_id
      description: |-
        wish_cardの更新。

        親の親のwish_listに招待されている人のみ可能。
    delete:
      summary: wish_card delete
      tags:
        - wish_cards
      responses: {}
      operationId: delete-wishcards-wish_card_id
      description: |-
        wish_cardの削除。

        親の親のwish_listに招待されている人のみ可能。
  /wishcards:
    parameters: []
    post:
      summary: wish_card create
      tags:
        - wish_cards
      responses: {}
      operationId: post-wishcards
      description: |-
        wish_cardを作成する。

        指定したカテゴリーの所属wish_listに招待されている人のみ可能。
  '/albums/{album_id}':
    parameters:
      - schema:
          type: integer
        name: album_id
        in: path
        required: true
    get:
      summary: album get
      tags:
        - albums
      responses: {}
      operationId: get-albums-album_id
      description: |-
        アルバム詳細情報を取得する。

        アルバムに招待されている人のみ可能。
    put:
      summary: album update
      tags:
        - albums
      responses: {}
      operationId: put-albums-album_id
      description: |-
        アルバムを更新する。

        アルバムに招待されている人のみ可能。
    delete:
      summary: album delete
      tags:
        - albums
      responses: {}
      operationId: delete-albums-album_id
      description: |-
        アルバムを削除する。

        アルバムに招待されている人のみ可能。（ホストのみにすべき？）
  /albums:
    get:
      summary: album list get
      tags:
        - albums
      responses: {}
      operationId: get-albums
      description: 自分のアルバム一覧。
    post:
      summary: album create
      tags:
        - albums
      responses: {}
      operationId: post-albums
      description: アルバム新規作成。
  /memories:
    post:
      summary: memory create
      tags:
        - memories
      responses: {}
      operationId: post-memories
      description: 思い出の新規作成。
components:
  schemas: {}
