openapi: 3.0.0
info:
  title: wantum
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/wishlists/{wish_list_id}':
    parameters:
      - schema:
          type: integer
        name: wish_list_id
        in: path
        required: true
    get:
      summary: wish_list get
      tags:
        - wish_lists
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/wish_lists.v1.yaml
      operationId: get-wishlists-wish_list_id
      description: |-
        wish_list詳細情報を取得する。

        そのwish_listに招待されている人だけが見られる。

        category, wish_card をネストしたjsonを返す。
    put:
      summary: wish_list update
      tags:
        - wish_lists
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  image_url:
                    type: string
                  invite_url:
                    type: string
                required:
                  - id
                  - title
                  - image_url
                  - invite_url
      operationId: put-wishlists-wish_list_id
      description: |-
        wish_listの更新。

        そのwish_listに招待されている人のみ可能（もしくはホストのみ？）。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: ''
    delete:
      summary: wish_list delete
      tags:
        - wish_lists
      responses:
        '200':
          description: OK
      operationId: delete-wishlists-wish_list_id
      description: |-
        wish_listの削除。

        そのwish_listに招待されている人のみ可能（もしくはホストのみ？）。
  /wishlists:
    post:
      summary: wish_list create
      tags:
        - wish_lists
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/wish_lists.v1.yaml
      operationId: post-wishlists
      description: wish_listの新規作成。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: 必要であれば画像を同時に送る
    parameters: []
    get:
      summary: wish_list list get
      operationId: get-wishlists
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    image_url:
                      type: string
                    invite_url:
                      type: string
                  required:
                    - id
                    - title
                    - image_url
                    - invite_url
      tags:
        - wish_lists
      description: |-
        wish_list一覧。

        自分の所持している全wish_listを返す。

        レスポンスjsonは、category, wish_card をネストしない。
  '/categories/{category_id}':
    parameters:
      - schema:
          type: integer
        name: category_id
        in: path
        required: true
    put:
      summary: category update
      tags:
        - categories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/categories.v1.yaml
      operationId: put-categories-category_id
      description: |-
        カテゴリーの更新。

        親のwish_listに招待されている人のみ可能。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
    delete:
      summary: category delete
      tags:
        - categories
      responses:
        '200':
          description: OK
      operationId: delete-categories-category_id
      description: |-
        カテゴリーの削除。

        親のwish_listに招待されている人のみ可能。
  /categories:
    parameters: []
    post:
      summary: category create
      tags:
        - categories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/categories.v1.yaml
      operationId: post-categories
      description: |-
        カテゴリーの新規作成。

        指定したwish_listに招待されている人のみ可能。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                wish_list_id:
                  type: integer
              required:
                - title
                - wish_list_id
  '/wishcards/{wish_card_id}':
    parameters:
      - schema:
          type: integer
        name: wish_card_id
        in: path
        required: true
    put:
      summary: wish_card update
      tags:
        - wish_cards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/wish_cards.v1.yaml
      operationId: put-wishcards-wish_card_id
      description: |-
        wish_cardの更新。

        親の親のwish_listに招待されている人のみ可能。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activity:
                  type: string
                description:
                  type: string
                date:
                  type: string
                category_id:
                  type: integer
                place_id:
                  type: integer
    delete:
      summary: wish_card delete
      tags:
        - wish_cards
      responses:
        '200':
          description: OK
      operationId: delete-wishcards-wish_card_id
      description: |-
        wish_cardの削除。

        親の親のwish_listに招待されている人のみ可能。
  /wishcards:
    parameters: []
    post:
      summary: wish_card create
      tags:
        - wish_cards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/wish_cards.v1.yaml
      operationId: post-wishcards
      description: |-
        wish_cardを作成する。

        指定したカテゴリーの所属wish_listに招待されている人のみ可能。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activity:
                  type: string
                description:
                  type: string
                date:
                  type: string
                category_id:
                  type: integer
                place_id:
                  type: integer
              required:
                - activity
                - description
                - category_id
                - place_id
  '/albums/{album_id}':
    parameters:
      - schema:
          type: integer
        name: album_id
        in: path
        required: true
    get:
      summary: album get
      tags:
        - albums
      responses: {}
      operationId: get-albums-album_id
      description: |-
        アルバム詳細情報を取得する。

        アルバムに招待されている人のみ可能。

        memoryをネストしたjsonを返す。
    put:
      summary: album update
      tags:
        - albums
      responses: {}
      operationId: put-albums-album_id
      description: |-
        アルバムを更新する。

        アルバムに招待されている人のみ可能。
    delete:
      summary: album delete
      tags:
        - albums
      responses: {}
      operationId: delete-albums-album_id
      description: |-
        アルバムを削除する。

        アルバムに招待されている人のみ可能。（ホストのみにすべき？）
  /albums:
    get:
      summary: album list get
      tags:
        - albums
      responses: {}
      operationId: get-albums
      description: 自分のアルバム一覧。
    post:
      summary: album create
      tags:
        - albums
      responses: {}
      operationId: post-albums
      description: アルバム新規作成。
  /memories:
    post:
      summary: memory create
      tags:
        - memories
      responses: {}
      operationId: post-memories
      description: |-
        思い出の新規作成。

        指定したwish_cardは削除される。
  /memories/timeline:
    get:
      summary: memory timeline
      tags:
        - memories
      responses: {}
      operationId: get-memories-timeline
      description: |-
        タイムライン。

        memoriesをcreated_atの新しい順で返す。
  '/memories/{memory_id}/wishcards':
    parameters:
      - schema:
          type: integer
        name: memory_id
        in: path
        required: true
    post:
      summary: wish_card create by memory
      tags:
        - wish_cards
      responses: {}
      operationId: post-memories-memory_id-wishcards
      description: |-
        memoryをPickしてwish_cardを作成。

        指定したcategoryの親wish_listに招待されている人のみ可能。
  '/profiles/{profile_id}':
    parameters:
      - schema:
          type: integer
        name: profile_id
        in: path
        required: true
    get:
      summary: profile get
      tags:
        - profiles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/profiles.v1.yaml
        '':
          content:
            application/json:
              schema:
                $ref: ../models/profiles.v1.yaml
          description: OK
      operationId: get-profiles-profile_id
      description: |-
        ユーザのプロフィールを取得する。

        レスポンスjsonにはユーザのmemoryも含む。

        （公開・非公開機能が実装された場合：他人には公開のものが、本人には公開・非公開いずれも取得できる）
  /profiles:
    put:
      summary: profile update
      tags:
        - profiles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/profiles.v1.yaml
      operationId: put-profiles
      description: プロフィール情報の更新。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                bio:
                  type: string
                gender:
                  type: integer
                phone:
                  type: string
                place:
                  type: string
                birth:
                  type: string
          multipart/form-data:
            schema:
              type: object
              properties: {}
    post:
      summary: profile create
      tags:
        - profiles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/profiles.v1.yaml
      operationId: post-profiles
      description: |-
        プロフィール情報の新規作成。

        既に作成済みの場合エラー。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                bio:
                  type: string
                gender:
                  type: integer
                phone:
                  type: string
                place:
                  type: string
                birth:
                  type: string
              required:
                - name
                - gender
                - phone
                - birth
          multipart/form-data:
            schema:
              type: object
        description: サムネイル画像も同時に送る。
  /auth/signup:
    post:
      summary: signup
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/users.v1.yaml
      operationId: post-auth-signup
      description: ユーザ新規登録。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
              required:
                - user_name
  /auth/signin:
    get:
      summary: signin
      operationId: get-auth-signin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/users.v1.yaml
      tags:
        - users
      description: |-
        ユーザログイン。

        ヘッダにJWTを持たせてリクエストを送ってください。
components:
  schemas: {}
