# CI 静的解析(fmt, lint)、テストのフローを自動化
# トリガー: 全ブランチに対するPR
name: CI

on:
    pull_request:
        branches:
            - '*'

env:
    # go.sumに変化がない時にキャッシュを更新したい場合は、変更してください
    cache-version: v1

jobs:
    # static-check: fmt, lint
    static-check:
        name: StaticCheck
        runs-on: ubuntu-latest

        steps:
            # set up go
            -   name: Set up Go 1.14
                uses: actions/setup-go@v1
                with:
                    go-version: 1.14
                id: go

            -   name: Check out code into the Go module directory
                uses: actions/checkout@v2

            # Run fmt
            -   name: Go fmt
                run: |
                    GO111MODULE=off go get -u golang.org/x/tools/cmd/goimports
                    gofmt -s -w .
                    ~/go/bin/goimports -w .

            # Run lint
            -   name: Go Lint
                run: |
                    GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint
                    ~/go/bin/golangci-lint run

    # test go test
    test:
        name: Test
        runs-on: ubuntu-latest
        needs: [ static-check ]
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306:3306
                options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
                env:
                    MYSQL_USER: worker
                    MYSQL_PASSWORD: password
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_DATABASE: wantum

        steps:
            # set up go
            -   name: Set up Go 1.14
                uses: actions/setup-go@v1
                with:
                    go-version: 1.14
                id: go

            -   name: Check out code into the Go module directory
                uses: actions/checkout@v2

            # set up db
            -   name: SetUp db
                run:
                    mysql --protocol=tcp -u root -ppassword wantum < ./db/mysql/init.d/ddl.sql
                    mysql --protocol=tcp -u root -ppassword wantum < ./db/mysql/init.d/dml.sql

            # Cache
            -   name: Cache go module
                uses: actions/cache@v1
                id: cache-go
                with:
                    path: ~/go/pkg/mod
                    key: ${{ env.cache-version }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                    restore-keys: |
                        ${{ env.cache-version }}-${{ runner.os }}-go-

            # Install modules
            -   name: Get dependencies
                if: steps.cache-go.outputs.cache-hit != 'true'
                run: |
                    go get -v -t -d ./...

            # Run test
            -   name: Test
                run: go test -v ./...

    # slackの通知
    slack-notification:
        name: Slack Notification
        runs-on: ubuntu-latest
        needs: [test, static-check]
        if: always()
        steps:
            -   uses: actions/checkout@v2

            -   uses: technote-space/workflow-conclusion-action@v1

            # 失敗時
            -   name: Slack Notification Failure
                if: env.WORKFLOW_CONCLUSION == 'failure'
                uses: rtCamp/action-slack-notify@v2.0.0
                env:
                    SLACK_CHANNEL: notify-server
                    SLACK_ICON: https://github.com/actions.png?size=48
                    SLACK_COLOR: '#ff0000'
                    SLACK_TITLE: 'static check & test is failure!!!'
                    SLACK_MESSAGE: |
                        CI failure!
                        See more detail to check github.
                        https://github.com/TechCafeFreedom/Wantum-server/actions
                    SLACK_USERNAME: GitHub Actions
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

            # 成功時
            -   name: Slack Notification Success
                if: env.WORKFLOW_CONCLUSION == 'success'
                uses: rtCamp/action-slack-notify@v2.0.0
                env:
                    SLACK_CHANNEL: notify-server
                    SLACK_ICON: https://github.com/actions.png?size=48
                    SLACK_TITLE: 'static check & test success!'
                    SLACK_MESSAGE: |
                        CI Success!
                    SLACK_USERNAME: GitHub Actions
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
